displayName: Debt Transformation TTP Requests
description: "This is an endpoint for testing the ttp service in different env - not to be used apart from debt transformation"
(annotations.sandboxData): !include ../../scenarios/deleteResponse.md
(annotations.scope): "read:debt-transformation-stub"
securedBy: [ sec.x-application: { scopes: [ "read:debt-transformation-stub" ] } ]
responses:
  200:
    body:
      text/plain:
        type: !include ../../schemas/deleteSchema.json
